### ISSUE TITLE
OpenTelemetry configuration using appsettings.json

### ISSUE THREAD

**Issue by cecilphillip** [serilog/serilog-sinks-opentelemetry#102]
How would you set this Sink up using the Serilog settings provider for Microsoft.Extensions.Configuration?
```json
 "WriteTo": [
      { "Name": "OpenTelemetry",  "Args": { 
          "Endpoint" : "http://127.0.0.1:4317", "ResourceAttributes" : ["??"]} 
      }
    ],
```

**Comment by bartelink** [comment]
In general, SO is the place to go for questions like this - the config syntax is orthogonal to the sink so finding config people and/or intersection of these watching this repo is lower (but post a link to it here...)

**Comment by nblumhardt** [comment]
Hi @cecilphillip 👋 

I don't think the JSON configuration syntax has support for dictionary values - I could be wrong, if I am it'll look like:

```json
 "WriteTo": [
      { "Name": "OpenTelemetry",  "Args": { 
          "Endpoint" : "http://127.0.0.1:4317", "ResourceAttributes" : {"service.name": "Example", "other": "Example2"} 
      }
    ],
```

(Would be great if we could support this; Serilog.Settings.Configuration would be the place to look.)

HTH!

**Comment by cecilphillip** [comment]
@nblumhardt Thanks boss

**Comment by nblumhardt** [comment]
Raised again in #103; I'll move it to `serilog-settings-configuration` :-)

**Comment by cecilphillip** [comment]
@nblumhardt  I'll take some solace in knowing that I wasn't the only one 🙂
