### ISSUE TITLE
Unable to send logs to OpenTelemetry backend (using Serilog in .Net framework 4.8) 

### ISSUE THREAD

**Issue by pvsunilkumar** [serilog/serilog-sinks-opentelemetry#109]
I am using Serilog in .Net Framework 4.8 to send logs to Opentelemetry. I am using Elastic as OpenTelemetry backend . I am able to send traces and but not logs. Please find my below code where it writes the log to the file but not sending logs to opentelemetry. Can somebody help?

        // TRACES ----- WORKING 
        _tracerProvider = Sdk.CreateTracerProviderBuilder()
       .AddAspNetInstrumentation()
       .AddHttpClientInstrumentation()
       .AddOtlpExporter(config =>
       {
           config.Endpoint = new Uri("https://abcd.es.io:443");
           config.Headers = "Authorization=ApiKey xyz";
       })
       .AddSource("SK")
       .SetResourceBuilder(
           ResourceBuilder.CreateDefault()
               .AddService(serviceName: "SCI", serviceVersion: "1.0.0")
               .AddAttributes(resourceAttributes))
       .Build();

       var endpoint = "https://abcd.es.io:443/v1/logs";
       var protocol = OtlpProtocol.HttpProtobuf;

       // LOGGING --- NOT WORKING
       Log.Logger = new LoggerConfiguration()
       .MinimumLevel.Error()
       .WriteTo.Console()
       .WriteTo.File(@"c:\tt\1.txt")
       .WriteTo.OpenTelemetry(
       options => {
            options.Endpoint = endpoint;
            options.Protocol = protocol;
            options.IncludedData =
                    IncludedData.SpanIdField
                    | IncludedData.TraceIdField
                    | IncludedData.MessageTemplateTextAttribute
                    | IncludedData.MessageTemplateMD5HashAttribute;
            options.ResourceAttributes = new Dictionary<string, object>
            {
                ["service.name"] = "SCI-NLogger",
                ["index"] = 10,
                ["flag"] = true,
                ["pi"] = 3.14
             };
             options.Headers = new Dictionary<string, string>
             {
             	["Authorization"] = "Basic xyz", // user:abc123
             };
             options.BatchingOptions.BatchSizeLimit = 2;
             options.BatchingOptions.Period = TimeSpan.FromSeconds(2);
             options.BatchingOptions.QueueLimit = 10;
         })
         .CreateLogger();

I tried "ApiKey" instead of "Basic" in the authorization header, but still it doesn't work. It writes the log successfully to the text file though.  Please help.

Followed this page [https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/example/Example/Program.cs](url) as reference.

**Comment by bartelink** [comment]
while this is a new sink (and he ce the knowledge of how to best use it might well reside in the heads of watchers here), may I still recommend asking this in SO Q&A format and pasting a link here? It'll hepl others in the future, and might help you in the near term as it will allow others to chime in with alternate ways they resolved it and/or drive by suggestions etc

**Comment by Kielek** [comment]
Ref: https://stackoverflow.com/questions/77165597/unable-to-send-logs-to-opentelemetry-backend-using-serilog-in-net-framework-4

**Comment by nblumhardt** [comment]
SO post has now been deleted; unsure why but guessing that an answer is no longer needed, so closing here, too.
