### ISSUE TITLE
accept standard OpenTelemetry environmental variables for configuration

### ISSUE THREAD

**Issue by loomis** [serilog/serilog-sinks-opentelemetry#12]
See the [OpenTelemetry environmental variable definitions](https://opentelemetry.io/docs/reference/specification/protocol/exporter/).

**Comment by loomis** [comment]
@nblumhardt Is there another sink that uses the `IOptions` pattern for configuration? I'm finding it difficult to understand how to integrate this and a concrete example would be helpful.

**Comment by nblumhardt** [comment]
Splitting `WriteTo.OpenTelemetry(..)` might need to be split into the one we have today, and one that accepts an `IConfiguration` or similar and no additional args.

Trying to meld the two (explicit parameters for endpoints etc. + default ones from configuration) seems fraught with difficulties, so better if the user decides which style they're after.

IIRC the _Serilog.Sinks.MSSqlServer_ sink does some special options support along these lines (not sure if it's the model to follow, but might help).

HTH!

**Comment by loomis** [comment]
Thanks! Will take a look.

**Comment by nblumhardt** [comment]
Just adding another note for when we're back around to this; the typical way for Serilog to interact with external configuration is via `ReadFrom.X()` where `X()` today is one of `Configuration()`/`Settings()`/`KeyValuePairs()`.

Given that the OTel variables are already defined and won't conform to any schema Serilog currently recognizes, we might be best off adding a `ReadFrom.OpenTelemetryEnvironment()` option that would just do the obvious thing - look for environment variables and (internally) pass these to `WriteTo.OpenTelemetry()` in strongly-typed args.

There's no restriction preventing e.g. an `IConfiguration`, or a bunch of defaults, being passed through to the `ReadFrom` extension, either.

**Comment by collinkostichuk-unity3d** [comment]
The opentelemetry-dotnet project's [OtlpExporterOptions class](https://github.com/open-telemetry/opentelemetry-dotnet/blob/45cf7c3a25f768eca0a1b944120a4d28ae6ae33f/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs) might be a helpful example of merging these environment variables with dotnet's Options pattern.

**Comment by AlbertoMonteiro** [comment]
@nblumhardt I've created a PR #141 

Can you review please?

**Comment by prochnowc** [comment]
@AlbertoMonteiro I found another environment variables which seems to be missing in the PR:

OTEL_SERVICE_NAME https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_service_name

**Comment by nblumhardt** [comment]
@prochnowc `4.0.0-dev-00317` now includes this.

**Comment by prochnowc** [comment]
@nblumhardt Many thanks. It's really helpfull when using Aspire.
