### ISSUE TITLE
Discussion: How to pass message template to WriteTo.OpenTelemetry() method?

### ISSUE THREAD

**Issue by sharifmamun** [serilog/serilog-sinks-opentelemetry#124]
In one of my existing setup, I am using a message template with WriteTo.Console() like below:
`.WriteTo.Console(outputTemplate: MessageTemplate) // here, MessageTemplate is a const with an output template`

How can I achieve the same with `WriteTo.OpenTelemetry()` or is it even possible?

**Comment by nblumhardt** [comment]
Hi! This would probably be achieved by specifying a custom `ITextFormatter` for the log record body, but it isn't implemented currently, and it's not certain we'll add it.

Another option which might take a few lines of code is to create a wrapper sink. This would accept `LogEvent` instances and use them to construct new, modified `LogEvent`s with the desired message format, and then forward these to the inner OTLP sink.

If you're interested in exploring this, _Serilog.Sinks.Async_ shows the mechanics of wrapper sinks in: https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/LoggerConfigurationAsyncExtensions.cs#L72 - HTH!

**Comment by sharifmamun** [comment]
Thanks @nblumhardt for the pointers. Here's what I did:

```
// wrapper as you suggested
public class OpenTelemetrySinkWrapper : ILogEventSink, IDisposable
{
    private readonly ILogEventSink _wrappedSink;
    private readonly string _messageTemplate;

    public OpenTelemetrySinkWrapper(ILogEventSink wrappedSink, string messageTemplate)
    {
        _wrappedSink = wrappedSink;
        _messageTemplate = messageTemplate;
    }

    public void Emit(LogEvent logEvent)
    {
        var template = new MessageTemplateParser().Parse(_messageTemplate);
        var boosted = new LogEvent(
            logEvent.Timestamp,
            logEvent.Level,
            logEvent.Exception,
            template,
            logEvent.Properties
                .Select(kvp => new LogEventProperty(kvp.Key, kvp.Value)));

        _wrappedSink.Emit(boosted);
    }

    public void Dispose()
    {
        (_wrappedSink as IDisposable)?.Dispose();
    }
}

// Logging class, using it in my services 
    public static class Logging
    {
        private const string PrefixTemplate = "[{Level:u3}][{Timestamp:o}][{Thread}][{SourceContext}]";
        private const string MessageTemplate = "{Message:lj}{NewLine}{Exception}";
        private const string GeneralMessageTemplate = $"{PrefixTemplate} {MessageTemplate}";

        private const string ThreadPropertyName = "Thread";

        public static IHostBuilder UseSerilog(this IHostBuilder hostBuilder)
        {
            Serilog.Debugging.SelfLog.Enable(Console.Error);

            return hostBuilder.UseSerilog((hostBuilderContext, loggerConfiguration) =>
            {
                // Here we configure host Serilog logger.

                loggerConfiguration
                    // Logger configuration is read from host configuration (typically, "Serilog" section in appsettings.json file).
                    .ReadFrom.Configuration(hostBuilderContext.Configuration, new ConfigurationReaderOptions(DependencyContext.Default))
                    .Enrich.With<HostContextEnricher>()
                    // Hard code the console sink.
                    //.WriteTo.Console(outputTemplate: GeneralMessageTemplate)
                    .WriteTo.EnhancedOpenTelemetry(GeneralMessageTemplate, wt => wt.OpenTelemetry(options =>
                    {
                        options.ResourceAttributes = new Dictionary<string, object>
                        {
                            ["service.name"] = hostBuilderContext.HostingEnvironment.ApplicationName
                        };

                        options.Endpoint = "http://host.docker.internal:4318/v1/logs";
                        options.Protocol = OtlpProtocol.HttpProtobuf;
                    }));
            }, preserveStaticLogger: true);
        }
}

// Extensions class 
public static class OpenTelemetryLoggerConfigurationExtensions
{
    public static LoggerConfiguration EnhancedOpenTelemetry(
        this LoggerSinkConfiguration lsc,
        string messageTemplate,
        Action<LoggerSinkConfiguration> writeTo)
    {
        return LoggerSinkConfiguration.Wrap(
            lsc,
            wrapped => new OpenTelemetrySinkWrapper(wrapped, messageTemplate),
            writeTo);
    }
}
```

Now, I am getting output like below (just the template), please note: Serilog.Sinks.Console has implementations like this: https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Sinks/SystemConsole/Output/OutputTemplateRenderer.cs to process the template.
![image](https://github.com/serilog/serilog-sinks-opentelemetry/assets/2019689/289d35fb-4a08-4065-afd5-2f7ea65f9deb)

However, I am trying to achieve something like below:
![image](https://github.com/serilog/serilog-sinks-opentelemetry/assets/2019689/8d386af0-cf8a-4c18-82ee-896db2b1e1a2)

Please let me know your thought if what I am trying to achieve is  doable without writing a lot more code.

**Comment by nblumhardt** [comment]
Hi @sharifmamun,

It's slightly more complicated, but you're very close. It should be something like:

```csharp
        var outputTemplate = new MessageTemplateParser().Parse(_messageTemplate);
        var outputFormatter = new MessageTemplateTextFormatter(outputTemplate);
        var message = outputFormatter.Format(logEvent);
        var template = new MessageTemplate(new[] { new TextToken(message) });
        var boosted = new LogEvent(
            logEvent.Timestamp,
            logEvent.Level,
            logEvent.Exception,
            template,
            logEvent.Properties
                .Select(kvp => new LogEventProperty(kvp.Key, kvp.Value)));
```

(Note you may need to create a `StringBuilder` in there for the `Format` call, I've bashed this together in the browser comment box so it's a rough approximation.)

HTH,
Nick

**Comment by sharifmamun** [comment]
With a little bit of tweaking on Format call, I have achieved what I actually needed. Thank you so much 💯.

**Comment by nblumhardt** [comment]
🙌

**Comment by CharlieDigital** [comment]
Question related to this:

When I add Serilog as the logger, the log now shows the formatted string:

<img width="1352" height="239" alt="Image" src="https://github.com/user-attachments/assets/f81c51d9-7724-4519-95c1-70da4bbea2c4" />

With the default `ILogger`, it shows the _formatting template_ string instead (reducing the cardinality of the logs):

<img width="1352" height="239" alt="Image" src="https://github.com/user-attachments/assets/5d8fc431-74d4-4467-890e-c04b1e8fc27d" />

Is the above the only way of achieving the desired output of having the template as the logged message?

**Comment by nblumhardt** [comment]
Hi! No, the `IncludedData.TemplateBody` option (https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/src/Serilog.Sinks.OpenTelemetry/Sinks/OpenTelemetry/IncludedData.cs#L76) does this. See: https://github.com/serilog/serilog-sinks-opentelemetry/tree/dev?tab=readme-ov-file#configuring-included-data

**Comment by CharlieDigital** [comment]
Ah; appreciate the tip.  That definitely worked.

Question though: 

- All log messages should go to OpenTelemetry
- Only the messages from certain namespaces should be logged with the template body
- Messages from default namespaces should be logged with the fully hydrated message

Would you then recommend the wrapped approach?  This is what I was working on before your note:

```cs
public void Emit(LogEvent logEvent)
{
    // Create a new LogEvent that preserves the original message template
    var modifiedLogEvent = new LogEvent(
        logEvent.Timestamp,
        logEvent.Level,
        logEvent.Exception,
        new MessageTemplateParser().Parse(
            logEvent.MessageTemplate.Text.Replace("{", "{{").Replace("}", "}}")
        ), // Keep the original template with placeholders
        logEvent.Properties.Select(kvp => new LogEventProperty(kvp.Key, kvp.Value))
    );

    _wrappedSink.Emit(modifiedLogEvent);
}
```

Also works.

Maybe `Condition`?
