### ISSUE TITLE
Issue with restrictedToMinimumLevel in appsetting.json

### ISSUE THREAD

**Issue by varnerknut** [serilog/serilog-sinks-opentelemetry#129]
I have issues using _restrictedToMinimumLevel_ in the appsettings.json file. 
It's working OK when bootstrapping in Program.cs, but not when using the json configuration. 

**Examples**

_Works fine:_
Program.cs
```c#
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .CreateBootstrapLogger();
builder.Host.UseSerilog((hostingContext, loggerConfiguration) =>
{
    loggerConfiguration.ReadFrom.Configuration(hostingContext.Configuration);
    loggerConfiguration.WriteTo.OpenTelemetry((options) =>
    {
        options.Endpoint = "http://127.0.0.1:4317";
        options.Protocol = OtlpProtocol.Grpc;
        options.RestrictedToMinimumLevel = LogEventLevel.Information;
    });
});
``` 

_Does not work (RestrictedToMinimumLevel is ignored, and will use default minimumlevel)_
Program.cs
```c#
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .CreateBootstrapLogger();
builder.Host.UseSerilog((hostingContext, loggerConfiguration) =>
{
    loggerConfiguration.ReadFrom.Configuration(hostingContext.Configuration);
});
``` 
appsettings.json
```
"Serilog": {
    {
      "Name": "OpenTelemetry",
      "Args": {
        "endpoint": "http://127.0.0.1:4317",
        "protocol": "Grpc", 
        "restrictedToMinimumLevel": "Information"
      }
    }
  ]
}
``` 

Expected: All logentries are on information level
Actual: All logentries are on minimum level (in my case debug)

**Comment by nblumhardt** [comment]
Thanks for the note :+1:. Serilog sinks normally, by convention, include `restrictedToMinimumLevel` and `levelSwitch` in their configuration methods, but those args are missing from the configuration overload you're calling:

https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/src/Serilog.Sinks.OpenTelemetry/OpenTelemetryLoggerConfigurationExtensions.cs#L86

Using the same parameter names, docs, and semantics as those args on `WriteTo.Console()` or any other core sink should make this a reasonably straightforward change, if someone has a chance to send a PR.

**Comment by CloudeaSoft** [comment]
> Thanks for the note 👍. Serilog sinks normally, by convention, include `restrictedToMinimumLevel` and `levelSwitch` in their configuration methods, but those args are missing from the configuration overload you're calling:
> 
> https://github.com/serilog/serilog-sinks-opentelemetry/blob/dev/src/Serilog.Sinks.OpenTelemetry/OpenTelemetryLoggerConfigurationExtensions.cs#L86
> 
> Using the same parameter names, docs, and semantics as those args on `WriteTo.Console()` or any other core sink should make this a reasonably straightforward change, if someone has a chance to send a PR.

I tried to code for this issue, can those codes working correctly?

**Comment by varnerknut** [comment]
Hi and thanks for the bugfix on this. 
I see that it has been merged and it would be really helpful to have a new release including this fix :)
Thank you very much for your help.

**Comment by CloudeaSoft** [comment]
Glad that i could be of help! 💖

**Comment by bartelink** [comment]
@CloudeaSoft there should be a -dev nuget? https://www.nuget.org/packages/Serilog.Sinks.OpenTelemetry/#versions-body-tab
(you can close this when you validate?)

**Comment by varnerknut** [comment]
Any news on the release?

**Comment by CloudeaSoft** [comment]
Sorry, I'm not really sure about the version control of the nuget package.

**Comment by nblumhardt** [comment]
I've just drafted the 2.0.0 release PR: https://github.com/serilog/serilog-sinks-opentelemetry/pull/135

Is anyone able to confirm that the 2.0.0-dev-* packages work as expected for them? Thanks!

**Comment by nblumhardt** [comment]
Released now :+1:
