### ISSUE TITLE
Review `Exception` mapping

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-opentelemetry#14]
The current implementation serializes exceptions as their message, type, and stack trace. While for many exceptions this is useful, for others (such as `TargetInvocationException` and `AggregateException`) it is less so.

Further to this, .NET exceptions often carry additional properties or generic `Data` that is useful for their interpretation.

The Serilog.Exceptions project has been running for many years with the goal of providing useful serialization of many .NET exception types (sometimes with considerable difficulty!).

I think we may be better off in the long term if we defer to the Serilog.Exceptions enricher for exception capturing/serialization, as other sinks do, and consider using the generic `ToString()` representation of exceptions to generate a single attribute in this sink.

(When Serilog.Exceptions is used, we might also allow the default representation to be switched off?)

Needs some more thought and investigation :-)

**Comment by julealgon** [comment]
> The Serilog.Exceptions project has been running for many years with the goal of providing useful serialization of many .NET exception types (sometimes with considerable difficulty!).
> 
> I think we may be better off in the long term if we defer to the Serilog.Exceptions enricher for exception capturing/serialization, as other sinks do, and consider using the generic `ToString()` representation of exceptions to generate a single attribute in this sink.

That sounds like a vastly more modular approach to me so I'm in. Documentation for this repo should mention that integration path so consumers are aware that if they want to, they can change/augment how exceptions are written using `Serilog.Exceptions` enricher.

**Comment by loomis** [comment]
PR #14 has a proposed solution for this issue. Feel free to review/merge, if it looks reasonable.

**Comment by loomis** [comment]
@nblumhardt Please review the changes in #20; merge it if you're OK with them.
