### ISSUE TITLE
A Serilog sink that'd use OpenTelemetry SDK

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog-sinks-opentelemetry#159]
First, I want to make clear that this is not a feature request for `Serilog.Sinks.OpenTelemetry`, as this is very obviously contrary to its original design decision. It's just that I haven't found a better place to ask this question.

Is there any Serilog sink implementation that would rely on OpenTelemetry SDK?

The rationale is that _if_ the system already uses OpenTelemetry SDK, the dependencies are not an issue, and going through the SDK for logs would allow them to share settings and, e.g., Resource definitions.

**Comment by nblumhardt** [comment]
Hi @srogovtsev!

I think @CodeBlanch had one of these in the works; I'm not sure where it landed, it may just be waiting to hit the top of the backlog :-) IIRC the project name was OpenTelemetry.Serilog.Sink.

If you're keen to dig in and put one of these together independently I'd be happy to help out. I don't have a use case for it myself so not much of an opportunity to dogfood, and no bandwidth to ship or maintain it, unfortunately, but I'm curious what it would look like and how smooth the integration can get.

**Comment by srogovtsev** [comment]
Let's say, I'm interested at trying my hand at it, but I don't know what my workload would be either. But in our particular case it might be a more reasonable approach than trying to adapt `Serilog.Sinks.OpenTelemetry` to all our needs.

**Comment by srogovtsev** [comment]
Were it not for the overhead, this could have been achieved by simply chaining [`Serilog.Sinks.ILogger`](https://github.com/TinyBlueRobots/Serilog.Sinks.ILogger) and OpenTelemetry's own integration for `M.E.L`. But the overhead would be unreasonable.

**Comment by srogovtsev** [comment]
Just as a record, it seems that I was too hasty with this idea: OpenTelemetry 1.9.0 (the latest at the time of writing) is very closed WRT logging infrastructure, so doing this right now seems unfeasible. But I'll keep an eye on it, and also dig somewhat.

**Comment by julealgon** [comment]
> OpenTelemetry 1.9.0 (the latest at the time of writing) is very closed WRT logging infrastructure, so doing this right now seems unfeasible.

What do you mean by that @srogovtsev ? Doesn't it expose an implementation of `Microsoft.Extensions.Logging.ILogger`?

**Comment by srogovtsev** [comment]
I mean that while it exposes an implementation of `Microsoft.Extensions.Logging.ILogger`, it doesn't expose _telemetry_-level primitives (i.e. there's no way to construct a [`LogRecord`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/core-1.9.0/src/OpenTelemetry/Logs/LogRecord.cs)).

Using `Microsoft.Extensions.Logging.ILogger` will mean doing double conversion (first from Serilog to M.E.L, and then from M.E.L to OpenTelemetry), and not having ability to pass some data (e.g. `Body` or TraceId/SpanId) directly, which is also far from optimal.

**Comment by nblumhardt** [comment]
I just had a quick poke around, I think the needed API is still `internal` in stable releases but might be available in prerelease packages: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4433

**Comment by ParadiseFallen** [comment]
+1

**Comment by nblumhardt** [comment]
Closing as this isn't something we can implement here in this repo, but feel free to drop a link in here if you build or spot one of these out there. Thanks for the discussion @srogovtsev :+1:

**Comment by srogovtsev** [comment]
It's been a long time, but I think I would leave a small update: somewhere during the winter a tried to implement this idea, but it turned out that - at least at that time, but I am yet to see whether something has changed in that regard - Microsoft's implementation, specifically [`LogRecordAttributeList.Export`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/60a383959120656871e0b4c97c91b297241d746c/src/OpenTelemetry.Api/Logs/LogRecordAttributeList.cs#L215) didn't support exporting nested data structures - which, considering Serilog's capabilities in this area, is a very big disadvantage.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @srogovtsev.

I implemented this one a while back: https://github.com/serilog/serilog-sinks-opentelemetrysdk - but, it relies on experimental SDK features, and I haven't spent any time at the level of detail your comment above digs into.

Would love to have your thoughts and collaboration over there, if this is still on your radar. Currently it's parked, for me, but mostly because I don't know how to move it forward without baked support in the SDK. The .NET OTel SDK maintainers indicated that they have some other priorities in the queue. Might be good to do a fresh survey of what's happening over there, in case some of this has opened up since then.
