### ISSUE TITLE
 Crash when OTEL_EXPORTER_OTLP_HEADERS contains '=' in the value of an header

### ISSUE THREAD

**Issue by fuji97** [serilog/serilog-sinks-opentelemetry#162]
**Description**
Using `=` in the value of a header in the `OTEL_EXPORTER_OTLP_HEADERS` environment variables causes a crash with the error:
```
System.InvalidOperationException: Invalid header format `XXXXX` in OTEL_EXPORTER_OTLP_HEADERS environment variable.
```
This is fairly important because the Authorization header uses a base64 encoded string that often ends with one or multiple '='.
If it should be URL-encoded, then the string is not decoded before being sent.

**Reproduction**
Just adding the `.WriteTo.OpenTelemetry()` with the `OTEL_EXPORTER_OTLP_HEADERS` environment variable set will cause crash the code.
```dotenv
OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic dXNlcm5hbWU6cGFzc3dvcmQ=" // username:password
```
```csharp
Log.Logger = new LoggerConfiguration()
                .WriteTo.OpenTelemetry()
                .CreateLogger();
```
Error:
```
System.InvalidOperationException: Invalid header format `Authorization=Basic dXNlcm5hbWU6cGFzc3dvcmQ=` in OTEL_EXPORTER_OTLP_HEADERS environment variable.
```

**Expected behavior**
Being able to use `OTEL_EXPORTER_OTLP_HEADERS` to send a valid Authorization header by either correctly parsing the default string or by decoding an URL-encoded one.

**Relevant package, tooling and runtime versions**
ASP.NET 8
Serilog.Sinks.OpenTelemetry: 4.1.0

**Additional context**
From what I've understand, this happens because, when parsing `OTEL_EXPORTER_OTLP_HEADERS`, the string is split by using `=` as separator and then the code checks if the resulting array size is exactly 2. I think this could be solved by splitting only on the first `=`.

**Comment by nblumhardt** [comment]
Thanks for the report! https://github.com/open-telemetry/opentelemetry-go/issues/2110#issuecomment-884316593 appears to explain the spec format for these values (in my quick scan I couldn't find a definitive source, but a few threads point back to this one).

**Comment by fuji97** [comment]
Yes, from the official [OpenTelemetry documentation](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#specifying-headers-via-environment-variables) I've found that the pairs should be formatted using the [W3C Baggage](https://www.w3.org/TR/baggage/#header-content) format.
But other implementations are more lenient on this, for example, the official .NET OpenTelemetry exporter accept spaces and `=` without issues.

**Comment by nblumhardt** [comment]
Fixed - building a patch release now: https://github.com/serilog/serilog-sinks-opentelemetry/pull/164
