### ISSUE TITLE
Plan of attack/call-to-action

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-opentelemetry#2]
I've dug into the official OpenTelemetry libraries for .NET - there's a lot of machinery there, and it seems questionable to want to run it all side-by-side with Serilog (better to use one or the other).

From that point of view, given the ultimate simplicity of the OTel logs protocol, I think the sink will be more useful by taking a lightweight approach and implementing the protocol directly with HTTP or gRPC and protocol buffers.

Here's my current plan - anyone interested in lending a hand, please let me know :-)

 - [x] project/repo/CI setup
 - [x] generate gRPC client types based on the protocol spec; see e.g. `OpenTelemetry.Exporter.OpenTelemetryProtocol.csproj` in the `opentelemetry-dotnet` repo
 - [ ] implement a mapping from batched `LogEvent`s to `ExportLogsServiceRequest`s
 - [ ] figure out what the sink's `Options` type will look like - e.g. accept the collector's HTTP base URL, etc.
 - [ ] implement _Serilog.Sinks.PeriodicBatching_'s `IBatchedLogEventSink` to construct requests, blast them through an `HttpClient`
 - [ ] wire everything up through logger sink configuration extensions
 - [ ] make some calls on how ambient trace and span ids will be determined by the sink (i.e. either through enriched log events, or by collecting them directly)

... or something close to that!

**Comment by julealgon** [comment]
Something I'd like to mention here is that the OTEL group also defined a lot of environment variables for configuring various aspects, including export concerns, and basically every such setting has a well-defined default value.

If possible, the new sink should follow those as closely as possible for consistency and portability.

Some info here:
- https://opentelemetry.io/docs/reference/specification/protocol/exporter/

The general configuration page also mentions something regarding "log batching" which I'm not sure is something Serilog would honor as well (I'm assuming yes):
- https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/#batch-logrecord-processor

Regarding this:
> make some calls on how ambient trace and span ids will be determined by the sink (i.e. either through enriched log events, or by collecting them directly)

The original implementation might help:
- https://github.com/open-telemetry/opentelemetry-dotnet/blob/7fd37833711e27a02e169de09f3816d1d9557be4/src/OpenTelemetry/Logs/OpenTelemetryLogger.cs#L73

**Comment by loomis** [comment]
@nblumhardt I had created an implementation for a similar sink in a private repository. I've refactored it for gRPC and put it in a public repo ([serilog-opentelemetry-grpc](https://github.com/loomis/serilog-opentelemetry-grpc)). Please take a look. If the design choices that I made are consistent with your vision, I'm happy to put this into your skeleton and submit a pull request.

**Comment by julealgon** [comment]
> I've refactored it for gRPC and put it in a public repo ([serilog-opentelemetry-grpc](https://github.com/loomis/serilog-opentelemetry-grpc)).

@loomis keep in mind a full implementation will eventually support all 3 serialization formats:
- `grpc`
- `http/proto`
- `http/json`

Based on that, I think having "grpc" as part of the project/repo name is not the way to go for the final implementation.

**Comment by nblumhardt** [comment]
@loomis looks great! 😎 

RE design choices, I think that's something to work out over time; there's a lot of precedent out there to follow, both in the Serilog ecosystem and (emerging) in OTel, so the path forwards should be pretty clear in the early stages.

Definitely happy to accept a PR 👍

**Comment by loomis** [comment]
@nblumhardt I'll fork the repo, migrate the content, and create a PR from there. I'll add the standard Serilog copyright to the files. Any other administrative things that I should look out for?

**Comment by nblumhardt** [comment]
None I can think of. Thanks!

**Comment by nblumhardt** [comment]
Now that we're out the gate I think we should close this and work from smaller/focused issues and PRs.
