### ISSUE TITLE
provide packages for multiple .NET versions

### ISSUE THREAD

**Issue by loomis** [serilog/serilog-sinks-opentelemetry#23]
Provide binaries for at least .NET framework 4.7.2+ and .NET core 6 (already available).

**Comment by SimonCropp** [comment]
@loomis would net48 suffice? given it is trivial to update from net472 to net48

**Comment by nblumhardt** [comment]
Not sure exactly what is meant, here, but turning `<TargetFramework>net6.0</TargetFramework>` into `<TargetFrameworks>net6.0,net472</TargetFrameworks>` in the CSPROJ should be enough.

**Comment by loomis** [comment]
Seems like supporting the [same targets as the OpenTelemetry .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet/blob/31cf72973f87c2ca161b6e214b21a4b8a4d1c415/src/OpenTelemetry/OpenTelemetry.csproj#L4) would be the best bet.
