### ISSUE TITLE
provide support for older .NET frameworks

### ISSUE THREAD

**Issue by loomis** [serilog/serilog-sinks-opentelemetry#28]
`System.Diagnostics.ActivityTraceId` and `ActivitySpanId` are not supported in any .NET Standard or .NET Framework version, only [Core 3.0+](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitytraceid).

There is a desire to support the older runtimes to be consistent with support from the OpenTelemetry .NET SDK, which supports:

- net6.0
- netstandard2.1
- netstandard2.0
- net462

Provide relevant compiler directives to ensure that the library builds on these targets.

**Comment by loomis** [comment]
@nblumhardt Let's discuss here what needs to be done to get this built for the older runtimes. Of the three that aren't working, the most useful one (from my point of view) is the net462. 

Thanks for diagnosing the build problem arising from this!

**Comment by nblumhardt** [comment]
👍 I think it would be awesome to support the older frameworks, but I actually have no idea how much of the heavy lifting is performed by those missing types.

Options might be:

 1. use `#if` directives to introduce our own (minimal) definitions for them on frameworks that don't have them
 2. as for (1), but use our own types on all frameworks
 3. break our dependency on them (somehow; e.g. by simply not including them on frameworks that don't support them)
 4. try to ship a v1 of the sink, and leave downlevel framework support for a follow-up release

I think 3 and 4 seem like the quickest ways to get up and running, though again, I'm not that confident I'm across the problem yet :-)

**Comment by SimonCropp** [comment]
would it be easier to release a "functionally duplicate" nuget that targets the OpenTelemetry .NET SDK?

**Comment by loomis** [comment]
If it is really just the `ActivityTraceId` and `ActivitySpanId` that are the problem, I think that the easiest would be to just not compile the TraceIdEnricher for the older runtimes. It'll take a little effort to separate the utilities linked to those fields, but not much. If at all possible, I'd like v1 to have support for at least net462.

It would be possible to target the OpenTelemetry .NET SDK. However, there are many downsides to this, first of which is that it brings in a huge number of dependencies. We've already had issues trying to resolve compatible versions of everything in production code. In addition, it doesn't expose the low-level protobuf definitions, so we'd still have to pull that in to do the conversion to the OpenTelemetry format. If at all possible, I'd like to avoid a direct dependency on the OpenTelemetry .NET SDK.

**Comment by julealgon** [comment]
> In addition, it doesn't expose the low-level protobuf definitions, so we'd still have to pull that in to do the conversion to the OpenTelemetry format. If at all possible, I'd like to avoid a direct dependency on the OpenTelemetry .NET SDK.

Just wanted to share a comment here which might be relevant. I'm pretty sure the .NET OTEL team is working on isolating the "transport" concerns into separate assemblies with potentially some sort of "Abstractions" common package, so that gRPC stuff is not included everywhere by default.

I don't think that separation is in place yet, but it might end up being by the time you guys get closer to finishing this up, so I figured you'd want to be aware.

When they do that, it might make sense to also then have a separate gRPC Serilog exporter, separate from the normal json one, for similar reasons (people not using the gRPC path would not add the Serilog gRPC package).
