### ISSUE TITLE
Nothing is pushed out on v0.4.0-dev-00073

### ISSUE THREAD

**Issue by lukasz-krzykowski** [serilog/serilog-sinks-opentelemetry#29]
Serilog.Sink.OpenTelemetry ([0.4.0-dev-00073](https://www.nuget.org/packages/Serilog.Sinks.OpenTelemetry/0.4.0-dev-00073)) seems not to be working at all - we stumbled for a few hours investigating why our logs/events were not ingested to telemetry collector - as it turns out, after changing the endpoint to anything else (e.g. https://webhook.site/) it looks like this release has some sort of problem and nothing is pushed whatsoever. Downgrading to [0.2.0-dev-00059](https://www.nuget.org/packages/Serilog.Sinks.OpenTelemetry/0.2.0-dev-00059) restores expected behavior (edited)

**Comment by lukasz-krzykowski** [comment]
We are only using Http, so that was the only one I've tested on (both versions)

**Comment by loomis** [comment]
Apologies for the problem. A fixed version has been pushed out (0.5.0) and should appear shortly.
