### ISSUE TITLE
Support standard exporter environment variables: OTEL_EXPORTER_OTLP_ENDPOINT and OTEL_EXPORTER_OTLP_LOGS_ENDPOINT

### ISSUE THREAD

**Issue by rcdailey** [serilog/serilog-sinks-opentelemetry#35]
My understanding based on the [open telemetry dotnet config docs](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#otlp) is that if you specify the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable, it will use that as the URL for the otel collector.

I'd like the default behavior to be changed, as I see it documented in the [main readme](https://github.com/serilog/serilog-sinks-opentelemetry#endpoint-and-protocol):

> The default endpoint is http://localhost:4317/v1/logs, which will send logs to an OpenTelemetry collector running on the same machine over the gRPC protocol. This is appropriate for testing or for using a local OpenTelemetry collector as a proxy for a downstream logging service.

I recommend that the endpoint be obtained by using the following rules, in descending order of precedence:

1. The value for the `endpoint` parameter in code, if specified.
1. Rules are followed for the [OLTP environment variables](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp), which is as follows (these rules are exactly the same as the linked specification):
    1. If the `OTEL_EXPORTER_OTLP_LOGS_ENDPOINT` environment variable is defined, use it as-is with no further change.
	1. Otherwise, use the `OTEL_EXPORTER_OTLP_ENDPOINT` variable, if defined, with `/v1/logs` appended to the end of that string.
1. Use the current default of `http://localhost:4317/v1/logs`.

**Comment by julealgon** [comment]
This is absolutely essential for the Serilog integration to play well with existing environments.

We've been using the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable ourselves extensively across many different projects. It would be a bad experience to have to customize it differently for Serilog in particular when adding it.

Also keep in mind that there is a variable specifically for the logging endpoint as well, which should also be respected by Serilog:

`OTEL_EXPORTER_OTLP_LOGS_ENDPOINT`

It is documented here:
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options

**Comment by rcdailey** [comment]
> Also keep in mind that there is a variable specifically for the logging endpoint as well, which should also be respected by Serilog

Excellent point. I actually didn't even know about this one. I will update my OP to include it.

**Comment by rcdailey** [comment]
I apologize, I just realized someone already reported this in #12. If you'd like to close this issue in favor of that one, I completely understand. I will point out that the other issue doesn't go into quite enough detail, so if you do close this one I don't mind adding a detailed comment there.

**Comment by rcdailey** [comment]
@nblumhardt Please provide a link to the issue that this one duplicates (based on the `duplicate` label you added). Thank you.
