### ISSUE TITLE
Consider using OpenTelemetry.SupressInstrumentationScope to cleanup tracing

### ISSUE THREAD

**Issue by Nefarion** [serilog/serilog-sinks-opentelemetry#41]
The dotnet OTEL Log exporter does this to hide its requests from tracing.

[See it here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a46039a39be484ff979ca31d7ed61aac5309381e/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpLogExporter.cs#L75)

**Comment by nblumhardt** [comment]
Hi @smbecker, thanks for the heads-up. Would it be possible to get some more repro details so we can investigate? I'm assuming your traces are collected using something like the setup in https://github.com/datalust/seq-examples/blob/main/client/opentelemetry-csharp-sdk-to-seq/weather/Program.cs - a fork of that example or similar would be great.

**Comment by jscarle** [comment]
I also have the same issue.

**Comment by badgeratu** [comment]
I have the same issue as well. Simple to reproduce - just add the [OpenTelemetry gRPC Instrumentation library](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.GrpcNetClient) to any project, and you'll see when using the OpenTelemetry OTLP Logs exporter you don't get these extra lines, but when using the Serilog OTLP Logs exporter you do.

**Comment by nblumhardt** [comment]
Thanks for all the feedback!

I've put a proposal together in #150 and you can grab the .NUPKGs with it directly from CI:

https://ci.appveyor.com/project/serilog/serilog-sinks-opentelemetry/builds/50393260/artifacts

Before merging this one I'm keen to validate that it covers your scenarios so if you're able to, please either grab the package, or the source code from my PR branch, and give it a try. Thanks! 😎

**Comment by nblumhardt** [comment]
The `-dev-00333` build, on its way through CI now, includes this.
