### ISSUE TITLE
Log events not setting field ObservedTimestamp

### ISSUE THREAD

**Issue by ewilansky** [serilog/serilog-sinks-opentelemetry#44]
Description: When using the serilog OpenTelemetry sink, the otlp collector ObservedTimestamp field always returns  the default unset value of 1970-01-01 00:00:00 +0000 UTC, as shown in this abbreviated log entry:

```
LogRecord #1
c-otel-1  | ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
c-otel-1  | Timestamp: 2023-04-07 21:25:47.4 +0000 UTC
c-otel-1  | SeverityText: Information
c-otel-1  | SeverityNumber: Info(9)
...
c-otel-1  | Trace ID: 86f248a85d1246f2853a1f7606150b07
c-otel-1  | Span ID: 435f8df3f827a19b
```

Expectation: I see that the Timestamp field is correctly set. I expected that the ObservedTimestamp field would also get this value. I might misunderstand how this is supposed to work, but this text about the OpenTelemetry log data model <https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md> about this field suggests that it should be getting set:

_For events originating externally and collected by OpenTelemetry (e.g. using Collector) this is the time when OpenTelemetry's code observed the event measured by the clock of the OpenTelemetry code. This field SHOULD be set once the event is observed by OpenTelemetry._

Maybe this has nothing to do with the Serilog OpenTelemetry sink, please advise.

**Comment by nblumhardt** [comment]
Thanks for the note. I think this field indicates when the event was collected, it's not something Serilog's code should be setting. HTH!

**Comment by nblumhardt** [comment]
Also - which ultimate destination are you sending your logs to? (It's possible the field might be set when it reaches that?)
