### ISSUE TITLE
Code style consistency - no explicit `private`, underscored fields, lowercase name for built-in `String` type

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-opentelemetry#5]
Just spotted a couple of discrepancies with the other Serilog projects, brought through via the initial import:

```csharp
    private readonly ResourceLogs resourceLogsTemplate;

    private static String? GetScopeName()
    {
        ...
```

should be:

```csharp
    readonly ResourceLogs _resourceLogsTemplate;

    static string? GetScopeName()
    {
        ...
```

**Comment by julealgon** [comment]
The lack of explicit `private` is fairly nonstandard. Is there a strong reason you went with that Nic?

**Comment by nblumhardt** [comment]
Thanks for the replies!

@julealgon in general the Serilog codebases aim for minimizing line noise; if something can be left out/implied it generally is. Over the years I've found cases where I've wanted to push against this from time to time, but always end up coming around once my eyes are retrained. Less code to read is pretty universally a good thing, unless it leads to ambiguity.

All water under the bridge, now; until we have a universally accepted `dotnet format` (I miss this from the Rust world :-)) consistency is the major consideration.

@loomis unfortunately no explicit style guide; the Serilog repo's style is the reference point. I'm happy to send a PR on this one if you like, but I think the three things mentioned in the title are the only ones I'd worry about right now.

**Comment by loomis** [comment]
@nblumhardt Please review PR #13.

**Comment by julealgon** [comment]
> @julealgon in general the Serilog codebases aim for minimizing line noise; if something can be left out/implied it generally is. Over the years I've found cases where I've wanted to push against this from time to time, but always end up coming around once my eyes are retrained. Less code to read is pretty universally a good thing, unless it leads to ambiguity.
> 
> All water under the bridge, now; until we have a universally accepted `dotnet format` (I miss this from the Rust world :-)) consistency is the major consideration.

Have you considered following the StypeCop guide/analyzer until something like that happens? It is fairly well established. 

For example:
- [SA1400AccessModifierMustBeDeclared](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md)

Keep in mind that the more people use it, the more universally accepted it gets 😉
