### ISSUE TITLE
Consider making class OpenTelemetrySink public.

### ISSUE THREAD

**Issue by rachwal** [serilog/serilog-sinks-opentelemetry#58]
Consider changing access modifiers of class OpenTelemetry Sink with its dependent types from internal to public.

**Comment by julealgon** [comment]
Can you provide some more details about why you are making this suggestion @rachwal ? Is there some specific thing you are trying to do that you want to share?

**Comment by nblumhardt** [comment]
The `LoggerSinkConfiguration.Wrap()` function provides most of what was originally done using public sink types. We've managed to eliminate them in most other Serilog sinks because of the added difficulty of maintaining them, I don't think we'd want to vary that here without really strong reasons.

**Comment by loomis** [comment]
I'll try using `LoggerSinkConfiguration.Wrap()` within our wrapper library to see if this satisfies the use case. (FYI, @rachwal.)

**Comment by loomis** [comment]
Added this as a 1.0.0 milestone issue for now. If suggested method works, this can be closed/removed.

**Comment by loomis-relativity** [comment]
The logging configuration method can be used for this use case; consequently, there's no need to make the OpenTelemetrySink class public.
