### ISSUE TITLE
Move less-frequently-used configuration options out of the inline `WriteTo.OpenTelemetry()` overload

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-opentelemetry#61]
Unsure exactly what these are; however, the argument list to the inline version is huge. Now that there's an alternative "options"-based API, we should review the arguments and strive to choose a stable/minimally complete set, leaving the others for the options callback.

**Comment by loomis** [comment]
I'd certainly be OK with using _only_ the options-based API. Would there be any downsides to supporting only that one?

If I had to choose a minimal set to leave in the inline version, I'd argue for just `endpoint`, `protocol`, and possibly `headers`. This would be enough to connect to most authenticated endpoints.

**Comment by nblumhardt** [comment]
The method-parameter-based API is currently needed to support _Serilog.Settings.Configuration_ (and _Serilog.Settings.AppSettings_, though we don't see much XML configuration these days :-)).

I think your suggested subset there is good, definitely the kind of thing I had in mind.

**Comment by loomis** [comment]
To summarize the ask for this issue: Support only `endpoint`, `protocol`, and `headers` in the inline options; everything else  is available only in the options-based API. Let just leave this ticket open to track that work.
