### ISSUE TITLE
Set default `service.name` and `telemetry.sdk.*` group according to spec

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-opentelemetry#77]
According to the spec, the resource attribute `service.name` must be set to a default value if not configured by the use:

https://opentelemetry.io/docs/specification/otel/resource/semantic_conventions/#service

And the telemetry SDK must attach various self-describing resource attributes:

https://opentelemetry.io/docs/specification/otel/resource/semantic_conventions/#telemetry-sdk

These are both called out in [Attributes with special handling](https://opentelemetry.io/docs/specification/otel/resource/semantic_conventions/#attributes-with-special-handling).

To me personally, these seem quite noisy and not universally useful. I'd love to leave this in the hands of the user, but on reading the spec today it doesn't seem that it would be the appropriate approach. Please prove me wrong if anyone can :-)

**Comment by julealgon** [comment]
Aren't telemetry-sdk attributes only added when you call `AddTelemetrySdk` on the `ResourceBuilder`? At least that's what I experience over here.

**Comment by nblumhardt** [comment]
Could be - but that seems out of sync with the spec, which is pretty clear on the group being mandatory 🤔

**Comment by julealgon** [comment]
> Could be - but that seems out of sync with the spec, which is pretty clear on the group being mandatory 🤔

That's so weird man.... you might wanna double check this with the folks in the contrib repo just in case.

Having an explicit method to add it while the spec is saying it is mandatory is such a big conflict.

**Comment by nblumhardt** [comment]
Thanks for taking a look! I'll try to find some supporting info 👍

**Comment by nblumhardt** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/4369

**Comment by loomis-relativity** [comment]
For these cases, I think that the OpenTelemetry sink falls in an odd location. Those requirements are really aimed at developers of full SDKs for particular programming languages. It makes sense that the full .NET OpenTelemetry SDK is following them. However, this sink is/will not be a full SDK; it only sends data provided by the developer to an OpenTelemetry endpoint.
I'd prefer to leave the decision to include these attributes to the developer and not insert any attributes of dubious value into the payload.

**Comment by nblumhardt** [comment]
Thanks for the reply @loomis-relativity 👍

I drew much the same conclusion about the dubious value of some of the attributes. More of these might be on the way as the spec grows, so I'm thinking about how to set consumers up for success with whatever collectors/targets might expect, while leaving some room to avoid payload bloat 🤔

I would personally turn the `telemetry.sdk.*` group attributes off in the environments I currently work in, whether from the .NET SDK or from this library, but I'd also assume that the sink would be conservative and align as closely to the spec as is reasonable by default. Some collectors might assume the presence of these attributes based on the spec, though, and degrade experience when they're absent. The spec doesn't really leave any room for the idea of "not using an SDK" (which is strange IMHO, but I'm not the one driving the spec ..).

What about if we were to use the `IncludedData` mechanism to control this? E.g. in the `IncludedData` flags, we'd include a new member `SpecRequiredResourceAttributes`, and only fill in missing `service.name` or `telemetry.sdk.*` attributes when the flag is set?

The sink would (I assume) include this flag in the default set, but we'd demonstrate leaving it out in examples showing how to customize included data, since I think that option will appeal to many users (me included :-)).

Thoughts?
