### ISSUE TITLE
Drop reference to OpenTelemetry.SemanticConventions

### ISSUE THREAD

**Issue by Kielek** [serilog/serilog-sinks-opentelemetry#78]
Consider to drop reference to `OpenTelemetry.SemanticConventions`.

This package should not be used in the production way. It is still in pre-release mode. What is more the way how it is generated can easily leads to binary incompatibility, even when the minor version is bumped.

Alternative approach:
copy file locally to your code and mark as internal/create some tailored version based on your needs.

Ongoing cleanup package task: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1100

Link: https://github.com/serilog/serilog-sinks-opentelemetry/blob/302b027fad94ae11a07ecf83c1e85a69405625de/src/Serilog.Sinks.OpenTelemetry/Serilog.Sinks.OpenTelemetry.csproj#L30

**Comment by Kielek** [comment]
@cijothomas, @utpilla FYI

**Comment by nblumhardt** [comment]
Thanks for the note @Kielek - this one slipped past us, definitely a worthwhile change 👍
