### ISSUE TITLE
How to use with OpenTelemetry configured to send to Azure App Insights?

### ISSUE THREAD

**Issue by cocowalla** [serilog/serilog-sinks-opentelemetry#80]
Hi, and thanks for this nice sink!

I'm using OpenTelemetry for metrics and traces, configured to export to Azure App Insights, something like:

```c#
services.AddOpenTelemetry()
	.WithTracing(tracing =>
	{
		tracing.AddAzureMonitorTraceExporter(options =>
		{
			options.ConnectionString = "My conn string";
		});
	})
	.WithMetrics(metrics =>
	{
		metrics.AddAzureMonitorMetricExporter(options =>
		{
			options.ConnectionString = "My conn string";
		});
	});

```

I'd like to get Serilog exporting logs to App Insights too - that does work using [serilog-sinks-applicationinsights](https://github.com/serilog-contrib/serilog-sinks-applicationinsights), but it means pulling in all the App Insights stuff, and I'm not sure it's even possible to switch off App Insights metrics and tracing while still allowing logs.

So, ideally I'd like logs to go through the Azure Monitor exporter, just like metrics and traces do.

What would be the recommended way to deal with this scenario please!

**Comment by nblumhardt** [comment]
Just checking in to say - I have no idea, unfortunately. Interested to hear how you go. Good luck!

**Comment by loomis-relativity** [comment]
Azure Monitor would need to provide an OTLP endpoint to capture logs sent from this sink. Currently, Azure Monitor does not provide such an endpoint. However, it appears to be on their roadmap based on [this question in their OpenTelemetry FAQ](https://learn.microsoft.com/en-us/azure/azure-monitor/faq#can-i-use-the-opentelemetry-collector-).
As a workaround until Azure provides an OTLP endpoint, you could run your own Collector bridge the OTLP to Azure Monitor translation. You'd use the[ Azure Monitor exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter) for this. At that point though, it is probably just easier to use the Azure Monitor sink instead.

**Comment by julealgon** [comment]
> At that point though, it is probably just easier to use the Azure Monitor sink instead.

The problem there @loomis-relativity is that vendor-locks your application.

We have a self-hosted OTEL collector in our environment for this purpose and I think that's a vastly better approach than configuring vendor-specific things on each project, especially if you have many of them. The collector can centralize the configuration in a single place that is much easier to change later.

**Comment by nblumhardt** [comment]
That's great to hear, thanks @cocowalla!

Given the breadth of different systems people will want to integrate with, and how quickly everything's churning out there, I don't think we should maintain samples or a knowledge-base in the project itself. We'd potentially end up with a lot of extra maintenance busywork updating the samples etc.

Adding what you can to this thread should still be enough for people to find it, if there isn't an obvious better destination?

**Comment by cocowalla** [comment]
@nblumhardt aye, you're probably right. I'll probably push it to a GitHub repo and link it from here instead

**Comment by cocowalla** [comment]
@Arash-Sabet something like this: https://gist.github.com/cocowalla/7b404cacf3bc4b742dd9ddb301c66c4c

**Comment by Arash-Sabet** [comment]
@cocowalla Thanks!

**Comment by cocowalla** [comment]
@Arash-Sabet Using the method I've shared, you should *not* call `WriteTo.OpenTelemetry`; actually, you don't even need this sink!

**Comment by julealgon** [comment]
> @Arash-Sabet Using the method I've shared, you should _not_ call `WriteTo.OpenTelemetry`; actually, you don't even need this sink!

I'm confused... aren't you just completely bypassing Serilog with your code? If you configure Serilog, and then add a second logger, the second logger won't receive anything that is configured using the Serilog API, such as enrichments etc.

Why do you even use Serilog at that point if you are just pushing logs directly to the native OTEL `ILogger`? The purpose of this sink here is to leverage Serilog functionality while still pushing to an OTEL-compatible endpoint.

If I'm correct with the above, I don't think your suggestion is a good one, personally.

**Comment by Arash-Sabet** [comment]
> > @Arash-Sabet Using the method I've shared, you should _not_ call `WriteTo.OpenTelemetry`; actually, you don't even need this sink!
> 
> 
> 
> I'm confused @cocowalla ... aren't you just completely bypassing Serilog with your code? If you configure Serilog, and then add a second logger, the second logger won't receive anything that is configured using the Serilog API, such as enrichments etc.
> 
> 
> 
> Why do you even use Serilog at that point if you are just pushing logs directly to the native OTEL `ILogger`? The purpose of this sink here is to leverage Serilog functionality while still pushing to an OTEL-compatible endpoint.
> 
> 
> 
> If I'm correct with the above, I don't think your suggestion is a good one, personally.

@julealgon I think @cocowalla suggested an interim solution as per my understanding Serilog's OTLP sink is not capable of sending data to Azure AI.

**Comment by cocowalla** [comment]
@julealgon 

> I'm confused @cocowalla ... aren't you just completely bypassing Serilog with your code? If you configure Serilog, and then add a second logger, the second logger won't receive anything that is configured using the Serilog API, such as enrichments etc.

No. Like many devs, I'm using Serilog enrichments, and I'm using Serilog to log to multiple sinks, including file, Windows Event Log, remote syslog, and also Azure App Insights. And when the data arrives in Azure AI, it's as nicely structured data, just as Serilog intended it :smile:

Enrichments are working just fine. Serilog handles all of my logging, but also "delegates" to the `OpenTelemetryLoggerProvider`, which in turn sends my logs to Azure AI.

> Why do you even use Serilog at that point if you are just pushing logs directly to the native OTEL ILogger? 

It's a bit strange to assume that's all I would be doing with Serilog. I see nothing wrong with my approach, and as I mentioned, I'm not *only* logging to Azure AI.

> The purpose of this sink here is to leverage Serilog functionality while still pushing to an OTEL-compatible endpoint.

Right, which, at least at the time of writing, does not help to get logs from Serilog into Azure AI - something I'm fairly sure a lot of devs will want to do.

> I don't think your suggestion is a good one, personally

This seems to be largely based on bad assumptions.

**Comment by Arash-Sabet** [comment]
I started feeling that I need more clarification on this Sink. Is it capable of sending telemetry logs to Azure Application Insights at all? What is supported and what is not supported by this Sink? How can we log `ActivitySource` and `TelemetrySpan` by this sink?

@cocowalla

**Comment by cocowalla** [comment]
@Arash-Sabet Azure Monitor [does not yet](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-overview#telemetry-routing) have an OpenTelemetry-compatible ingestion endpoint:

> Azure Monitor is developing an agent and ingestion endpoint that supports [Open Telemetry Protocol (OTLP)](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/README.md), providing a path for any OpenTelemetry-supported programming language ...  to use to Azure Monitor

So no, AFAIK this sink cannot yet send data to Azure Monitor (or App Insights) - but that's not this sink's fault, it's up to Azure to have an OTEL ingestion endpoint.

**Comment by Arash-Sabet** [comment]
@cocowalla Sounds fair. But the code you shared before is sending the data to App Insights in OLTP, isn't it?

**Comment by cocowalla** [comment]
> @cocowalla Sounds fair. But the code you shared before is sending the data to App Insights in OLTP, isn't it?

Yes... but without using this sink 😄 

Instead, it uses an Azure Monitor "exporter", which sits at the end of the OpenTelemetry pipeline and outputs data to Azure's non-OTEL compatible Monitor/App Insights endpoint.

**Comment by julealgon** [comment]
> @julealgon I think @cocowalla suggested an interim solution as per my understanding Serilog's OTLP sink is not capable of sending data to Azure AI.

Ok... I missed the `writeToProviders` parameter over there. That makes me even more confused though... why would you do that instead of just using the Azure sink?
- https://github.com/serilog-contrib/serilog-sinks-applicationinsights

If you want to log into Azure directly, there is no reason to make this "indirection" from Serilog back to ILogger using the OTEL exporter, IMHO.

> No. Like many devs, I'm using Serilog enrichments, and I'm using Serilog to log to multiple sinks, including file, Windows Event Log, remote syslog, and also Azure App Insights. And when the data arrives in Azure AI, it's as nicely structured data, just as Serilog intended it 😄

As per the above, why not just add the AppInsights sink into your chain?

 
> Enrichments are working just fine. Serilog handles all of my logging, but also "delegates" to the `OpenTelemetryLoggerProvider`, which in turn sends my logs to Azure AI.

My bad on missing the `writeToProviders` parameter. I've never used that one so I completely missed it. I understand how it is working for you now.

> It's a bit strange to assume that's all I would be doing with Serilog. I see nothing wrong with my approach, and as I mentioned, I'm not _only_ logging to Azure AI.

Sorry, the assumption came from my misunderstanding as per above.

> > I don't think your suggestion is a good one, personally
> 
> This seems to be largely based on bad assumptions.

I still think it is not a good suggestion considering it would be considerably more straightforward to just use the Azure sink instead.

Up to you (or others who want to adopt your suggestion) though.

The only exception would be if you want to export to other OTLP-compatible endpoints at the same time, which doesn't seem like what you need there in your example.

**Comment by cocowalla** [comment]
@julealgon

> why would you do that instead of just using the Azure sink?
> why not just add the AppInsights sink into your chain?
> I still think it is not a good suggestion considering it would be considerably more straightforward to just use the Azure sink instead.

There are many reasons why not to use the Azure sink, including:

- OTEL is fast becoming the industry standard - I _want_ to use it; why on earth would I choose a system based on a proprietary protocol, when something better exists?
- I've used the App Insight sink before in previous projects, but configuring the underlying App Insights stuff "just how I want it", is a massive PITA, and feels like a constantly moving target - I don't want to use it
- I'm writing some metrics to places other than AI (database and disk), so it makes _no_ sense whatsoever to duplicate metrics collection, processing and reporting by both App Insights *and* the OTEL library - that would be... incredibly wasteful, at best
- While I'm using Azure App Insights for now, eventually I'll move to a self-hosted system (which will of course have an OTEL endpoint)

What I'm doing works, and works well - it's absolutely fine.
