### ISSUE TITLE
OpenTelemetry Specification compliance

### ISSUE THREAD

**Issue by pellared** [serilog/serilog-sinks-opentelemetry#86]
The approach of integrating Serilog with OpenTelemetry Logs is NOT compliant with [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.21.0/specification/logs).

The [OpenTelemtry SDK should accept a logger provider](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/logs/sdk.md#logger-creation) via [Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/logs/bridge-api.md) which is not done yet (see: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4433)

As far as I understand correctly, the Serilog Sink (["log appender"](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/logs/bridge-api.md#how-to-create-a-log4j-log-appender) in OpenTelemetry specification) would only have to depend on [`OpenTelemetry.Api` NuGet package](https://www.nuget.org/packages/OpenTelemetry.Api).

Maybe the fact that the design is not OpenTelemetry Specification compliant could be mentioned in the docs?

_Originally posted by @pellared in https://github.com/serilog/serilog-sinks-opentelemetry/issues/73#issuecomment-1550902983_

**Comment by nblumhardt** [comment]
The sink's aiming for compliance with the OpenTelemetry protocol. I'll call that out in the README 👍

**Comment by nblumhardt** [comment]
> The sink aims for full compliance with the OpenTelemetry Logs protocol. It
> does not depend on the OpenTelemetry SDK or .NET API.

Thanks!

**Comment by pellared** [comment]
That works fine and hopefully decreases potential confusion.  In future, there could be a separate Sink/adapter that would work with OpenTelemtry Logs Bridge API.

**Comment by nblumhardt** [comment]
Definitely! This is what _OpenTelemetry.Extensions.Serilog_ does, I think, so hopefully that will be the solid solution for those looking for integration into the SDK 👍
