### ISSUE TITLE
unknown service opentelemetry.proto.collector.logs.v1.LogsService

### ISSUE THREAD

**Issue by aliaa** [serilog/serilog-sinks-opentelemetry#94]
I tried the example project while a collector was running in my local. and I set Serilog inner log enabled:
```
Serilog.Debugging.SelfLog.Enable(Console.WriteLine);
```
And I saw this error in my console:
```
Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="unknown service opentelemetry.proto.collector.logs.v1.LogsService")
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

**Comment by nblumhardt** [comment]
Hi! Are you running a collector with a logs endpoint exposed? I don't think opentelemetry-collector receives logs by default, some config is required.

**Comment by julealgon** [comment]
> I don't think opentelemetry-collector receives logs by default, some config is required.

That's kind of a weird statement though Nic... the collector doesn't do _anything_ by default, all 3 pipelines need to be configured explicitly (metrics, logs, traces).

Maybe if @aliaa could share his collector yaml setup that would help.

Having said that, shouldn't this exception be handled? I can imagine a scenario where someone wants to turn off logging at the collector level and that IMHO shouldn't cause all applications to start throwing like this.

**Comment by nblumhardt** [comment]
The exception is handled, in this case - it's per batch, exponential back-off, on a background thread, and reported only through `SelfLog` 👍
