### ISSUE TITLE
Connection confusion in gRPC package

### ISSUE THREAD

**Issue by stoeren** [serilog/serilog-sinks-opentelemetry#97]
The current used version `2.50.0` of `Grpc.Net.Client` has an security issue of high severity.
Updating it to >=`2.52.0` would fix it.
https://github.com/advisories/GHSA-cfgp-2977-2fmm

**Comment by nblumhardt** [comment]
Thanks for the heads-up; PR #98 fixes this. On first reading of the advisory I can't quite see how it would affect the package when used as it is by this package, but no harm upgrading either way :+1:
